services:
  - type: web
    name: equalvoice-api
    env: python
    buildCommand: pip install -r requirements.txt && python nltk_setup.py

    startCommand: python nltk_setup.py && uvicorn main:app --host 0.0.0.0 --port 10000

    plan: free
    envVars:
      - key: PORT
        value: 10000
